import { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Html5Qrcode } from "html5-qrcode";
import { QrCode, ScanLine, XCircle, KeyboardIcon, CheckCircle2 } from "lucide-react";
import { Button } from "../components/ui/button";
import { Input } from "../components/ui/input";
import { api } from "../lib/api";
import { useLang } from "../context/LangContext";
import { toast } from "sonner";

/**
 * QR-scan admin page.
 *
 * Uses html5-qrcode to open the device camera (rear/environment) and scan
 * pawn-item labels generated by `/api/contracts/{cid}/label-pdf`. The QR
 * payload is JSON: {"cn": <contract_number>, "item": <name>, "id": <id>}.
 *
 * On successful decode the page:
 *   1. Stops the camera
 *   2. Hits `GET /api/contracts/{id}` to confirm the contract exists
 *   3. Navigates to /contracts?status=<status>&highlight=<cn>
 * so the warehouse staff lands on the exact row with the item context.
 *
 * If the QR is not one of ours (missing `cn`), a fallback lookup by
 * contract_number is attempted via `/api/contracts?contract_number=X` —
 * the search endpoint isn't specialised so we filter client-side.
 */
export default function Scan() {
  const { lang } = useLang();
  const T = (en, tet) => (lang === "tet" ? tet : en);
  const nav = useNavigate();
  const scannerRef = useRef(null);
  const [scanning, setScanning] = useState(false);
  const [error, setError] = useState("");
  const [manualCn, setManualCn] = useState("");
  const [lastScan, setLastScan] = useState(null);

  useEffect(() => {
    // Cleanup on unmount — very important, otherwise the camera stays on
    return () => {
      if (scannerRef.current) {
        scannerRef.current.stop().catch(() => {}).finally(() => {
          scannerRef.current = null;
        });
      }
    };
  }, []);

  const handleDecoded = async (rawText) => {
    // Prevent double-fire while we handle the first match
    if (lastScan === rawText) return;
    setLastScan(rawText);
    let payload = null;
    try {
      payload = JSON.parse(rawText);
    } catch {
      payload = null;
    }
    if (payload?.id) {
      // Direct contract id — best case, single hop
      try {
        await api.get(`/contracts/${payload.id}`);
        await stopScanner();
        toast.success(`Found: ${payload.cn}`);
        nav(`/contracts?highlight=${encodeURIComponent(payload.cn || payload.id)}`);
        return;
      } catch {
        // fall through to number lookup
      }
    }
    const cn = payload?.cn || rawText.trim();
    // Lookup by contract_number via the /contracts list (client-side filter)
    try {
      const r = await api.get("/contracts");
      const match = (r.data || []).find((c) => c.contract_number === cn);
      if (match) {
        await stopScanner();
        toast.success(`Found: ${cn}`);
        nav(`/contracts?highlight=${encodeURIComponent(cn)}`);
      } else {
        setError(T(`No contract found for "${cn}"`, `La iha kontratu ho "${cn}"`));
        setTimeout(() => { setLastScan(null); setError(""); }, 2000);
      }
    } catch (e) {
      setError(String(e?.response?.data?.detail || e.message || e));
    }
  };

  const startScanner = async () => {
    setError("");
    setLastScan(null);
    try {
      const el = document.getElementById("qr-scanner-region");
      if (!el) return;
      const scanner = new Html5Qrcode("qr-scanner-region", { verbose: false });
      scannerRef.current = scanner;
      await scanner.start(
        { facingMode: "environment" },
        { fps: 10, qrbox: { width: 240, height: 240 } },
        handleDecoded,
        () => {},
      );
      setScanning(true);
    } catch (e) {
      setError(
        T(
          "Camera not available. On desktop please use the manual entry below.",
          "Kamera la disponivel. Iha desktop favor uza kaixa manual iha okos.",
        ),
      );
      setScanning(false);
    }
  };

  const stopScanner = async () => {
    if (scannerRef.current) {
      try {
        await scannerRef.current.stop();
      } catch {}
      scannerRef.current = null;
    }
    setScanning(false);
  };

  const submitManual = async (e) => {
    e.preventDefault();
    if (!manualCn.trim()) return;
    await handleDecoded(manualCn.trim());
  };

  return (
    <div className="space-y-6" data-testid="scan-root">
      <header>
        <div className="text-eyebrow flex items-center gap-2">
          <ScanLine className="w-3.5 h-3.5" /> {T("Warehouse Lookup", "Buka Sasán")}
        </div>
        <h1 className="font-display text-2xl sm:text-3xl md:text-4xl font-semibold mt-1">
          {T("Scan QR Label", "Skaneia Etiketa QR")}
        </h1>
        <p className="text-stone-600 text-sm mt-1 max-w-2xl">
          {T(
            "Point the phone camera at the QR sticker on a pawned item to jump straight to its contract. If you don't have a camera, type the contract number below.",
            "Aponta kamera telemovel ba etiketa QR iha sasán ne'ebé penhor atu ba kedas kontratu. Se la iha kamera, hakerek numeru kontratu iha okos.",
          )}
        </p>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Camera panel */}
        <div className="p-5 rounded-lg border border-stone-200 bg-white space-y-4">
          <div className="flex items-center justify-between">
            <div className="text-eyebrow flex items-center gap-1.5">
              <QrCode className="w-3.5 h-3.5" /> {T("Camera", "Kamera")}
            </div>
            {scanning ? (
              <button
                onClick={stopScanner}
                data-testid="scan-stop-btn"
                className="text-xs px-2 py-1 rounded-md border border-red-200 text-red-700 hover:bg-red-50"
              >
                <XCircle className="w-3.5 h-3.5 inline mr-1" />
                {T("Stop", "Para")}
              </button>
            ) : (
              <Button
                onClick={startScanner}
                data-testid="scan-start-btn"
                className="bg-[#1B2D5C] hover:bg-[#0F1B3A] text-white text-sm"
              >
                <ScanLine className="w-4 h-4 mr-1" />
                {T("Start Camera", "Loke Kamera")}
              </Button>
            )}
          </div>
          <div
            id="qr-scanner-region"
            className="w-full rounded-md overflow-hidden bg-stone-100 min-h-[280px] flex items-center justify-center"
            data-testid="qr-scanner-region"
          >
            {!scanning && (
              <div className="text-stone-400 text-xs text-center px-6 py-14">
                <QrCode className="w-12 h-12 mx-auto mb-2 text-stone-300" />
                {T(
                  "Press \"Start Camera\" to begin scanning.",
                  "Klik \"Loke Kamera\" atu hahu skaneia.",
                )}
              </div>
            )}
          </div>
          {error && (
            <div
              data-testid="scan-error"
              className="text-xs text-red-700 bg-red-50 border border-red-200 rounded-md px-3 py-2"
            >
              {error}
            </div>
          )}
        </div>

        {/* Manual entry panel */}
        <div className="p-5 rounded-lg border border-stone-200 bg-white space-y-4">
          <div className="text-eyebrow flex items-center gap-1.5">
            <KeyboardIcon className="w-3.5 h-3.5" /> {T("Manual Entry", "Hakerek Manual")}
          </div>
          <p className="text-sm text-stone-600">
            {T(
              "Type or paste the contract number (e.g. CTR-2026-0042) — useful when the QR is damaged or the camera isn't available.",
              "Hakerek ka paste numeru kontratu (ex. CTR-2026-0042) — bainhira etiketa QR aat ka la iha kamera.",
            )}
          </p>
          <form onSubmit={submitManual} className="flex gap-2">
            <Input
              type="text"
              placeholder="CTR-2026-0042"
              value={manualCn}
              onChange={(e) => setManualCn(e.target.value)}
              data-testid="scan-manual-input"
              className="flex-1"
            />
            <Button
              type="submit"
              data-testid="scan-manual-submit"
              className="bg-[#4C7F62] hover:bg-[#3F6B52] text-white"
            >
              <CheckCircle2 className="w-4 h-4 mr-1" />
              {T("Find", "Buka")}
            </Button>
          </form>
          <div className="pt-2 text-xs text-stone-500">
            {T("Tip: ", "Sujestaun: ")}
            {T(
              "The camera needs HTTPS and permission — accept the browser prompt when it appears.",
              "Kamera presiza HTTPS no permisaun — aseita mensajen navegador nian.",
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
